chore: pushed new JSON-Schema
obsidianmd/jsoncanvas pull request #5
Opened 2024-03-11 23:39 UTC by chainlist

Added new JSON Schema for proper autocompletion

2024-03-14 09:19 UTC, dolmen requested changes

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +				},
Define a `NodeId` schema. That will help to give semantic info to properties like `fromNode`.

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +					"type": "number"
```suggestion
					"type": "integer"
```

2024-03-14 09:19 UTC, dolmen commented on schema.json
> +		"required": true,
There is no `required` property at "Top level".
```suggestion
```

2024-03-14 09:27 UTC, dolmen requested changes

2024-03-14 09:27 UTC, dolmen commented on schema.json
> +	"definitions": {
This must be `$defs`.

https://json-schema.org/draft/2020-12/json-schema-core#section-8.2.4

2024-03-14 09:27 UTC, dolmen commented on schema.json
> +	"$schema": "http://json-schema.org/draft-07/schema#",
Use latest spec instead: https://json-schema.org/specification
```suggestion
	"$schema": "https://json-schema.org/draft/2020-12/schema",
```

2024-03-15 15:13 UTC, metruzanca commented
Great idea! I was actually thinking the only things missing were a `schema.json` and `schema.ts` files. Not that they're "needed", but because the community would really appreciate it and might increase adoption.

2026-06-14 18:02 UTC, closed without merging